project:
  type: default
  output-dir: _output
  resources:
    - screenshots/plotly.min.js

format:
  revealjs:
    theme: [dark, custom.scss]
    transition: fade
    title-slide: false
    slide-number: true
    width: 1280
    height: 720
    margin: 0.03
    center: true
    hash-type: number
    navigation-mode: linear
    controls: true
    progress: true
    pdf-separate-fragments: false
